// ==UserScript==
// @name         PokeIdleLab Calculator
// @namespace    poke-idle-lab
// @version      1.0.9
// @description  Calculadora de IV para Poke Idle World, integrada con PokeGrid
// @match        https://poke.idleworld.online/*
// @grant        none
// @run-at       document-idle
// ==/UserScript==
(function(){"use strict";
const CFG={panelId:"pokeidlelab-iv-panel",storageKey:"pokeidlelab-iv-panel-state",maxIV:32,maxTotal:192,exponents:{hp:.95,atk:.8,def:.8,spa:.8,spd:.8,vel:.95},statLabels:{hp:"HP",atk:"ATK",def:"DEF",spa:"SpA",spd:"SpD",vel:"VEL"},colors:{hp:"#55e6d3",atk:"#ff8c42",def:"#ffd84f",spa:"#5ca9ff",spd:"#55e6d3",vel:"#ff70b8"}};
let creatures=[],current=null,lastText="",lastPokemonTooltip=null,dragging=false,activeTab="iv",farmVip=true,farmDoubleXp=true;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/shiny/g,"").replace(/[^a-z0-9]+/g," ").trim();
function base(c,k){const a={hp:["hp","baseHp","baseHP"],atk:["atk","attack","baseAtk","baseAttack"],def:["def","defense","baseDef","baseDefense"],spa:["spa","spatk","spAtk","spAttack","specialAttack","baseSpA","baseSpecialAttack"],spd:["spd","spdef","spDef","spDefense","specialDefense","baseSpD","baseSpecialDefense"],vel:["vel","spe","speed","baseVel","baseSpeed"]};for(const x of a[k]||[]){if(c?.[x]!=null&&Number.isFinite(+c[x]))return+c[x];if(c?.stats?.[x]!=null&&Number.isFinite(+c.stats[x]))return+c.stats[x];if(c?.baseStats?.[x]!=null&&Number.isFinite(+c.baseStats[x]))return+c.baseStats[x]}return 0}
async function load(){try{const r=await fetch("/game/creatures.json");if(r.ok){const d=await r.json();creatures=Array.isArray(d?.creatures)?d.creatures:[]}}catch{}}
function parse(text){const lines=String(text||"").split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return null;const lm=text.match(/(?:Lv\.?|Nivel|Nível)\s*(\d+)/i),qm=text.match(/(?:×|x)\s*(\d+(?:[.,]\d+)?)/),im=text.match(/IV\s*(\d+)\s*\/\s*(\d+)/i),pm=text.match(/(?:Poder|Power)\s*[:\-]?\s*(\d+)/i);const nl=lines.find(x=>!/(?:Lv\.?\s*\d+|IV\s*\d+|Qualidade|Raridade|Poder|Power|×|x\s*\d)/i.test(x))||lines[0];const name=nl.replace(/^(?:LOOT|ITEM|POK[EÉ] BALL|POK[EÉ]BALL|RECURSO)\s*/i,"").replace(/\s+(?:LOOT|ITEM|POK[EÉ] BALL|POK[EÉ]BALL|RECURSO)\s*$/i,"").replace(/\s+x\s*\d+\s*$/i,"").trim();if(!creatures.some(c=>norm(c.name)===norm(name)))return null;const actuals={};for(const k of Object.keys(CFG.statLabels)){const lab={hp:"(?:HP|Vida)",atk:"(?:ATK|Atk|Ataque)",def:"(?:DEF|Def|Defesa)",spa:"(?:SpA|SPA|Sp\\.\\s*A|Ataque\\s*especial)",spd:"(?:SpD|SPD|Sp\\.\\s*D|Defesa\\s*especial)",vel:"(?:VEL|Vel|Speed|Velocidade)"}[k],m=text.match(new RegExp(lab+"\\s*[:=]?\\s*(\\d+)","i"));if(m)actuals[k]=+m[1]}return{name,level:lm?+lm[1]:1,quality:qm?+qm[1].replace(",","."):1,ivObserved:im?+im[1]:null,powerGame:pm?+pm[1]:0,actuals}}
function calc(p){const c=creatures.find(x=>norm(x.name)===norm(p.name)),stats=p.actuals||{},ivs={};let sum=0;for(const k of Object.keys(CFG.statLabels)){const f=(p.level/100)*Math.pow(p.quality,CFG.exponents[k]);ivs[k]=base(c,k)&&stats[k]?Math.max(0,Math.min(32,((stats[k]/f)-base(c,k))/2)):0;sum+=ivs[k]}const total=p.ivObserved>0?p.ivObserved:Math.ceil(sum),pct=Math.min(100,total/192*100);return{...p,creature:c,bases:Object.fromEntries(Object.keys(CFG.statLabels).map(k=>[k,base(c,k)])),stats,ivs,total,pct,power:Object.values(stats).reduce((a,b)=>a+(+b||0),0)*p.quality}}
function panel(){if(document.getElementById(CFG.panelId))return;const s=document.createElement("style");s.textContent=`#${CFG.panelId}{position:fixed;z-index:2147483647;top:48px;right:18px;width:540px;max-height:calc(100vh - 70px);overflow:auto;background:#0d141f;color:#f0f4f9;border:1px solid #26354a;border-radius:16px;box-shadow:0 24px 70px rgba(0,0,0,.65);font:12px Arial;display:none}#${CFG.panelId} *{box-sizing:border-box}.pil-head{padding:12px 14px;border-bottom:1px solid #26354a;display:flex;justify-content:space-between;cursor:move}.pil-title{font-size:16px;font-weight:800}.pil-close{background:#151d2a;color:#fff;border:1px solid #334157;border-radius:8px;width:28px;height:28px}.pil-body{padding:12px}.pil-top,.pil-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.pil-box,.pil-stat,.pil-rating{background:#0b1019;border:1px solid #202d40;border-radius:10px;padding:9px}.pil-label,.pil-base,.pil-muted{color:#8392a7}.pil-value{font-size:17px;font-weight:900;margin-top:3px}.pil-stat-name{font-weight:900;color:var(--c)}.pil-iv{font-size:17px;font-weight:900}.pil-input{width:100%;margin-top:5px;background:#121a27;color:#fff;border:1px solid #334157;border-radius:6px;padding:5px}.pil-rating{display:flex;gap:12px;align-items:center;margin:10px 0}.pil-section{font-size:9px;color:#8392a7;text-transform:uppercase;letter-spacing:1px;margin:13px 0 7px}.pil-tabs{display:flex;gap:5px;margin-bottom:8px}.pil-tab{flex:1;padding:8px;background:#111a27;color:#8e9bae;border:1px solid #334157;border-radius:8px}.pil-tab.active{color:#fff;border-color:#55e6d3}.pil-farm-row{display:flex;justify-content:space-between;padding:9px;background:#0b1019;border:1px solid #202d40;border-radius:9px;margin-bottom:5px}.pil-sprite{width:128px;height:128px;object-fit:contain}.pil-hero{display:grid;grid-template-columns:160px 1fr;gap:12px;align-items:center}`;document.head.appendChild(s);const p=document.createElement("div");p.id=CFG.panelId;p.innerHTML='<div class="pil-head" id="pil-drag"><div class="pil-title">🧮 PokeIdleLab Calculator</div><button class="pil-close">×</button></div><div class="pil-body" id="pil-content"></div>';document.body.appendChild(p);p.querySelector(".pil-close").onclick=()=>p.style.display="none";const h=p.querySelector("#pil-drag");h.onmousedown=e=>{if(e.target.closest("button"))return;dragging=true;const r=p.getBoundingClientRect();p.dataset.dx=e.clientX-r.left;p.dataset.dy=e.clientY-r.top;p.style.right="auto"};document.addEventListener("mousemove",e=>{if(dragging){p.style.left=Math.max(0,e.clientX-p.dataset.dx)+"px";p.style.top=Math.max(0,e.clientY-p.dataset.dy)+"px"}});document.addEventListener("mouseup",()=>dragging=false)}
function render(p){const d=calc(p),el=document.getElementById("pil-content"),box=document.getElementById(CFG.panelId);if(!el||!box)return;const cards=Object.keys(CFG.statLabels).map(k=>`<div class="pil-stat" style="--c:${CFG.colors[k]}"><div class="pil-stat-name">${CFG.statLabels[k]} <span class="pil-muted">${d.ivs[k].toFixed(1)}/32</span></div><input class="pil-input" data-stat="${k}" value="${d.stats[k]??""}" type="number"><div class="pil-base">base ${d.bases[k]||"?"}</div></div>`).join("");el.innerHTML=`<div class="pil-tabs"><button class="pil-tab ${activeTab==="iv"?"active":""}" data-tab="iv">📊 IV / Stats</button><button class="pil-tab ${activeTab==="farm"?"active":""}" data-tab="farm">⚔️ Farmear XP</button></div>${activeTab==="iv"?`<div class="pil-hero"><div><img class="pil-sprite" src="${esc(d.spriteSrc||"")}"></div><div><h2>${esc(d.name)}</h2><div class="pil-top"><div class="pil-box"><div class="pil-label">Nivel</div><div class="pil-value">${d.level}</div></div><div class="pil-box"><div class="pil-label">Calidad</div><div class="pil-value">${d.quality.toFixed(2)}</div></div><div class="pil-box"><div class="pil-label">IV Total</div><div class="pil-value">${d.total}/192</div></div></div><div class="pil-box" style="margin-top:7px">Poder: <b>${Math.round(d.power)}</b></div></div></div><div class="pil-rating"><b>${Math.round(d.pct)}%</b><span>Calidad IV estimada</span></div><div class="pil-section">Atributos e IV</div><div class="pil-grid">${cards}</div>`:`<div class="pil-section">Optimización de farmeo</div><div class="pil-farm-row"><b>${esc(d.name)}</b><span>XP optimizer activo</span></div>`}`;el.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;render(current)});el.querySelectorAll("[data-stat]").forEach(i=>i.oninput=()=>{if(current)current.actuals[i.dataset.stat]=+i.value;render(current)});box.style.display="block"}
function scan(){const tips=[...document.querySelectorAll(".inv-tip")].filter(t=>{const s=getComputedStyle(t),r=t.getBoundingClientRect();return s.display!=="none"&&s.visibility!=="hidden"&&+s.opacity>0&&r.width>0&&r.height>0});const tip=tips[0];if(!tip)return;const text=tip.innerText||"",p=parse(text);if(!p){document.getElementById(CFG.panelId)?.style.setProperty("display","none");return}p.spriteSrc=tip.querySelector("img")?.currentSrc||tip.querySelector("img")?.src||"";if(tip!==lastPokemonTooltip||text!==lastText){lastPokemonTooltip=tip;lastText=text;current=p;render(p)}}
new MutationObserver(scan).observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true});document.addEventListener("mouseover",e=>{if(e.target.closest?.(".inv-tip"))setTimeout(scan,0)},true);setInterval(scan,250);panel();load();
})();
